### ISSUE TITLE
[Cloud] Safe mode not registered properly

### ISSUE THREAD

**Issue by kennethlimcp** [spark/cloud#11] opened 2016-06-04 15:06 UTC
Please sanitize/remove any confidential info like usernames, passwords, org names, product names/ids, access tokens, client ids/secrets, or anything else you don't wish to share.

Choose one of the following templates:

### Expected behavior

- Registers and updates the "status" attribute of the device upon entering safe mode
- Changes to Magenta status for the device

### Observed behavior

- Still displays as Cyan status for the device
- The device status endpoint does not show it in safe mode (i'm assuming safe mode is reflected in the device attribute)

### Steps to reproduce

- Place the device in safe mode
- Refresh the Device list in Build or Dashboard

**Comment by joegoggins** [comment] 2016-06-04 15:24
Hey Kenneth, thanks for the bug report, it appears one of the back-end service workers responsible for this was not-fully operational for the last 8 hours. Give it another shot. I've queued up an issue to look deeper into root cause and add additional alerts to avoid this in the future for Monday.

**Comment by kennethlimcp** [comment] 2016-06-05 01:04
@joegoggins, just placed a Photon in Safe-mode again but the ☁️  doesn't seem to pick it up/update the device attribute.

**Comment by kennethlimcp** [comment] 2016-08-12 16:09
@joegoggins did it got fixed?

**Comment by joegoggins** [comment] 2016-08-15 17:42
Thanks for the ping @kennethlimcp , yes, it was fixed the same day it was reported. Since then we've added multiple metrics and alerts to page us should a similar issue like this crop up again. Closing this here issue. 

👍

**Closed by joegoggins** 2016-08-15 17:42 UTC
