### ISSUE TITLE
[Web IDE] Duplicate files

### ISSUE THREAD

**Issue by ScruffR** [spark/cloud#59] opened 2019-02-04 19:00 UTC
Not always but quite often after having a set of `.h`/`.cpp` files added to a project after leaving the project and coming back to it, the files are duplicated but when you delete one set all respective files are gone.

**Comment by monkbroc** [comment] 2019-02-04 19:14
I don't think we'll ever figure out the duplicate tab bug of the Web IDE. Multiple people have looked into this over the past couple years and it's been one of those things we just can't reproduce reliably. Sorry.

**Comment by monkbroc** [comment] 2020-02-04 14:36
I implemented a workaround for the duplicate tab bug in Web IDE to delete the 2nd set of tabs. I'll close this issue and you can reopen it if you see it again.

**Closed as completed by monkbroc** 2020-02-04 14:36 UTC
Labels: wontfix
